spring:
  application:
    name: auth

server:
  port: ${port:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret: MY-SECRET-KEY-MUST-BE-256-BITS-LONG!!
    expiration: 86400000 #token expira em 1 dia, em milesegundos 

  oauth2:
    client:
      client-id: name123 
      client-secret: secret123