spring:
  application:
    name: turma

  profiles:
    active: test

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: ${port:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      professor:
        sliding-window-size: 10
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
      aluno:
        sliding-window-size: 10
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

feign:
  client:
    config:
      default:
        decode404: true