spring:
  application:
    name: aluno

  config:
    import: optional:configserver:http://config-server:8888

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always